eclipse/keyple-java

- README.md
- android/example/calypso/nfc/build.gradle
- android/example/calypso/omapi/build.gradle
- android/keyple-plugin/android-nfc/build.gradle
- android/keyple-plugin/android-omapi/build.gradle
- build.gradle
- java/component/keyple-calypso/build.gradle
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/po/parser/DecreaseRespPars.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/po/parser/IncreaseRespPars.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/sam/builder/security/DigestUpdateCmdBuild.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/sam/builder/security/GiveRandomCmdBuild.java
- java/component/keyple-calypso/src/test/java/org/eclipse/keyple/calypso/command/sam/builder/DigestCloseCmdBuildTest.java
- java/component/keyple-calypso/src/test/java/org/eclipse/keyple/calypso/command/sam/builder/DigestInitCmdBuildTest.java
- java/component/keyple-calypso/src/test/java/org/eclipse/keyple/calypso/command/sam/builder/DigestUpdateCmdBuildTest.java
- java/component/keyple-calypso/src/test/java/org/eclipse/keyple/calypso/command/sam/parser/SelectDiversifierRespParsTest.java
- java/component/keyple-core/build.gradle
- java/component/keyple-core/src/main/java/org/eclipse/keyple/seproxy/event/ObservableReader.java
- java/component/keyple-plugin/pcsc/build.gradle
- java/component/keyple-plugin/pcsc/src/main/java/org/eclipse/keyple/plugin/pcsc/PcscPlugin.java
- java/component/keyple-plugin/stub/build.gradle
- java/example/calypso/common/build.gradle
- java/example/calypso/pc/build.gradle
- java/example/calypso/remotese/build.gradle
- java/example/generic/common/build.gradle
- java/example/generic/pc/build.gradle
> change version to 0.7.0-SNAPSHOT -> develop

- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/po/parser/GetDataFciRespPars.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/util/bertlv/TLV.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/util/bertlv/Tag.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/util/bertlv/TLVTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/util/bertlv/TagTest.java
Removed dependency to com.sun.jndi.ldap.BerDecoder. 
Created new TLV management classes.
Fixes #37
> Added BER-TLV Tag.java and TLV.java management classes

- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/nativese/SlaveAPI.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/nativese/method/RmConnectReaderTx.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/nativese/method/RmDisconnectReaderTx.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/nativese/method/RmTransmitSetExecutor.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/MasterAPI.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/VirtualReader.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/method/RmSetDefaultSelectionRequestTx.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/method/RmTransmitSetTx.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/method/RmTransmitTx.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/rm/RemoteMethod.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/rm/RemoteMethodExecutor.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/rm/RemoteMethodTx.java
- java/component/keyple-plugin/stub/src/main/java/org/eclipse/keyple/plugin/stub/StubReader.java
seperate transmit from transmitset
#48 
> remotese : separate transmit and transmitset

- android/build.gradle
- android/example/calypso/nfc/build.gradle
- android/example/calypso/nfc/settings.gradle
- android/example/calypso/omapi/build.gradle
- android/example/calypso/omapi/settings.gradle
- android/gradle.properties
- android/keyple-plugin/android-nfc/build.gradle
- android/keyple-plugin/android-omapi/build.gradle
- android/settings.gradle
- build.gradle
- common.gradle
- gradle.properties
- java/component/build.gradle
- java/component/keyple-calypso/build.gradle
- java/component/keyple-core/build.gradle
- java/component/keyple-plugin/pcsc/build.gradle
- java/component/keyple-plugin/remotese/build.gradle
- java/component/keyple-plugin/stub/build.gradle
- java/example/calypso/common/build.gradle
- java/example/calypso/pc/build.gradle
- java/example/calypso/remotese/build.gradle
- java/example/generic/common/build.gradle
- java/example/generic/pc/build.gradle
- java/integration/build.gradle
- settings.gradle
#68 
Each night snapshots are published to sonatype via this jenkins job
https://jenkins.eclipse.org/keyple/job/keyple_publish_SNAPSHOT_DEVELOP_each_day
> Publish snapshots to maven

- android/build.gradle
- android/example/calypso/nfc/settings.gradle
- android/keyple-plugin/android-nfc/src/main/java/org/eclipse/keyple/plugin/android/nfc/AndroidNfcReader.java
- android/keyple-plugin/android-nfc/src/test/assets/logback.xml
- android/keyple-plugin/android-nfc/src/test/java/org/eclipse/keyple/plugin/android/nfc/AndroidNfcReaderTest.java
- android/settings.gradle
- build.gradle
- java/component/build.gradle
- java/component/keyple-calypso/build.gradle
- java/component/keyple-core/build.gradle
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/plugin/AbstractLocalReader.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/plugin/AbstractObservableReader.java
- java/component/keyple-plugin/pcsc/build.gradle
- java/component/keyple-plugin/remotese/build.gradle
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/nativese/INativeReaderService.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/nativese/SlaveAPI.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/nativese/method/RmConnectReaderTx.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/nativese/method/RmDisconnectReaderTx.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/RemoteSePlugin.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/RmConnectReaderExecutor.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/VirtualReader.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/rm/RemoteMethodTxEngine.java
- java/component/keyple-plugin/remotese/src/test/java/org/eclipse/keyple/plugin/remotese/integration/SlaveAPITest.java
- java/component/keyple-plugin/remotese/src/test/java/org/eclipse/keyple/plugin/remotese/pluginse/VirtualReaderTest.java
- java/component/keyple-plugin/stub/build.gradle
- java/example/calypso/remotese/src/main/java/org/eclipse/keyple/example/remote/transport/wspolling/client_retrofit/WsPRetrofitClientImpl.java
- java/example/calypso/remotese/src/main/java/org/eclipse/keyple/example/remote/transport/wspolling/server/EndpointPolling.java
- add observer in polling client
- add option to connect method #76 
- use SeReader instead of ProxyReader #65
> Remotese improvement

- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/po/parser/SelectFileRespPars.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/sam/CalypsoSamCommands.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/sam/builder/security/SamReadCeilingsCmdBuild.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/sam/builder/security/SamReadEventCounterCmdBuild.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/sam/builder/security/SamReadKeyParametersCmdBuild.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/sam/builder/security/SamWriteKeyCmdBuild.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/sam/parser/security/SamReadCeilingsRespPars.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/sam/parser/security/SamReadEventCounterRespPars.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/sam/parser/security/SamReadKeyParametersRespPars.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/sam/parser/security/SamWriteKeyRespPars.java
- java/integration/build.gradle
- java/integration/src/main/java/org/eclipse/keyple/integration/samData/SamCounterData.java
- java/integration/src/main/java/org/eclipse/keyple/integration/samData/SamKeyData.java
- java/integration/src/main/java/org/eclipse/keyple/integration/samData/SamStructureData.java
- java/integration/src/main/java/org/eclipse/keyple/integration/tools/calypso/Tool_AnalyzePoFileStructure.java
- java/integration/src/main/java/org/eclipse/keyple/integration/tools/calypso/sam/Tool_SAM_DisableLock.java
- java/integration/src/main/java/org/eclipse/keyple/integration/tools/calypso/sam/Tool_SAM_EnableLock.java
- java/integration/src/main/java/org/eclipse/keyple/integration/tools/calypso/sam/Tool_SAM_GetKeyParams.java
Added tools for SAM handling and analysis.
> Sam get key information

- android/keyple-plugin/android-nfc/build.gradle
- android/keyple-plugin/android-omapi/build.gradle
- java/component/keyple-calypso/build.gradle
- java/component/keyple-core/build.gradle
- java/component/keyple-plugin/pcsc/build.gradle
- java/component/keyple-plugin/remotese/build.gradle
- java/component/keyple-plugin/stub/build.gradle
- java/integration/src/main/java/org/eclipse/keyple/integration/tools/calypso/Tool_AnalyzePoFileStructure.java
start v0.8.0 branch for all components
> V0.8.0 init

- android/keyple-plugin/android-nfc/src/main/java/org/eclipse/keyple/plugin/android/nfc/AndroidNfcReaderImpl.java
- java/example/calypso/pc/build.gradle
- java/example/calypso/remotese/build.gradle
- java/example/generic/pc/build.gradle
- java/example/settings.gradle
- java/integration/build.gradle
- java/integration/settings.gradle
> Fix example build

- README.md
- java/example/calypso/pc/README.md
> Update root readme file with a note about symbolic links

- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/AbstractPluginFactory.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/SeProxyService.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/exception/KeyplePluginInstanciationException.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/plugin/local/AbstractObservableState.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/plugin/local/monitoring/CardAbsentPingMonitoringJob.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/plugin/local/monitoring/SmartInsertionMonitoringJob.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/plugin/local/monitoring/SmartRemovalMonitoringJob.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/SeProxyServiceTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/local/AbsSmartInsertionTheadedReaderTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/local/WaitForSeInsertionJobExecutorTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/local/WaitForSeInsertionTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/local/WaitForSeRemovalJobExecutorTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/local/WaitForSeRemovalTest.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/MasterAPI.java
- java/component/keyple-plugin/remotese/src/test/java/org/eclipse/keyple/plugin/remotese/integration/Integration.java
- java/component/keyple-plugin/remotese/src/test/java/org/eclipse/keyple/plugin/remotese/pluginse/VirtualReaderTest.java
- java/example/calypso/remotese/src/main/java/org/eclipse/keyple/example/remote/application/Demo_Master.java
- java/example/calypso/remotese/src/main/java/org/eclipse/keyple/example/remote/application/Demo_Slave.java
> seproxy : add exception when register plugin

- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/transport/model/DefaultTransportDto.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/transport/model/TransportDto.java
> add DefaultTransportDto

- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/local/WaitForSeInsertionTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/local/WaitForSeProcessingTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/local/WaitForSeRemovalJobExecutorTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/local/WaitForSeRemovalTest.java
- java/component/keyple-plugin/stub/src/test/java/org/eclipse/keyple/plugin/stub/StubPluginTest.java
> Improve flaky tests

- android/keyple-plugin/android-nfc/src/main/java/org/eclipse/keyple/plugin/android/nfc/AndroidNfcFragment.java
- android/keyple-plugin/android-nfc/src/main/java/org/eclipse/keyple/plugin/android/nfc/AndroidNfcPluginImpl.java
- android/keyple-plugin/android-omapi/src/main/java/org/eclipse/keyple/plugin/android/omapi/AndroidOmapiPluginFactory.java
- android/keyple-plugin/android-omapi/src/main/java/org/eclipse/keyple/plugin/android/omapi/AndroidOmapiPluginImpl.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/AbstractPluginFactory.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/ReaderPlugin.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/plugin/AbstractPlugin.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/SeProxyServiceTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/AbstractThreadedObservablePluginTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/mock/BlankFailingPlugin.java
- java/component/keyple-plugin/pcsc/src/main/java/org/eclipse/keyple/plugin/pcsc/PcscPluginFactory.java
- java/component/keyple-plugin/pcsc/src/main/java/org/eclipse/keyple/plugin/pcsc/PcscPluginImpl.java
- java/component/keyple-plugin/stub/src/main/java/org/eclipse/keyple/plugin/stub/StubPluginImpl.java
- java/component/keyple-plugin/stub/src/main/java/org/eclipse/keyple/plugin/stub/StubPoolPluginImpl.java
- java/example/calypso/android/omapi/src/main/java/org/eclipse/keyple/example/calypso/android/omapi/OMAPITestFragment.java
> remove exception in getReaders

- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/transaction/CalypsoPo.java
> Amélioration Javadoc release 0.8

- gradle/wrapper/gradle-wrapper.properties
> fix gradle version

- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/po/CalypsoPoCommands.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/po/builder/WriteRecordCmdBuild.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/po/parser/WriteRecordRespPars.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/transaction/PoTransaction.java
> Added the Write Record command the Calypso PO command set 

- ReleaseNotes.md
- android/gradle.properties
- gradle.properties
- java/example/calypso/android/nfc/gradle.properties
- java/example/calypso/android/omapi/gradle.properties
- java/example/gradle.properties
1. make keyple-java-example, android examples apk point to version "0.8.0"
2. edit readme.md
3. edit release note
4. set release flag to true
5. tag source code with tag : 0.8.0
Full process documented here :  
https://github.com/eclipse/keyple-java/wiki
> Release 0.8.0

- android/keyple-plugin/android-nfc/build.gradle
- android/keyple-plugin/android-omapi/build.gradle
- java/component/keyple-calypso/build.gradle
- java/component/keyple-core/build.gradle
- java/component/keyple-plugin/pcsc/build.gradle
- java/component/keyple-plugin/remotese/build.gradle
- java/component/keyple-plugin/stub/build.gradle
> fix pom for sonatype requirements

- java/example/calypso/pc/Demo_CalypsoClassic/build.gradle
- java/example/calypso/pc/UseCase1_ExplicitSelectionAid/build.gradle
- java/example/calypso/pc/UseCase2_DefaultSelectionNotification/build.gradle
- java/example/calypso/pc/UseCase3_Rev1Selection/build.gradle
- java/example/calypso/pc/UseCase4_PoAuthentication/build.gradle
- java/example/calypso/pc/UseCase5_MultipleSession/build.gradle
- java/example/generic/pc/Demo_SeProtocolDetection/build.gradle
- java/example/generic/pc/UseCase1_ExplicitSelectionAid/build.gradle
- java/example/generic/pc/UseCase2_DefaultSelectionNotification/build.gradle
- java/example/generic/pc/UseCase3_GroupedMultiSelection/build.gradle
- java/example/generic/pc/UseCase4_SequentialMultiSelection/build.gradle
That makes it easier to run one specific example outside of an IDE.
> Add run Gradle run taks for the Java examples

- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/nativese/SlaveAPI.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/nativese/method/RmConnectReaderTx.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/nativese/method/RmDisconnectReaderTx.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/nativese/method/RmPoolAllocateExecutor.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/nativese/method/RmPoolReleaseExecutor.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/MasterAPI.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/RemoteSePluginImpl.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/RemoteSePoolPluginImpl.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/RmPoolReleaseTx.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/rm/AbstractRemoteMethodTx.java
> fix: add slaveId in allocate reader API

- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/transaction/CalypsoPo.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/transaction/DirectoryHeader.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/transaction/ElementaryFile.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/transaction/FileData.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/transaction/FileHeader.java
- java/component/keyple-calypso/src/test/java/org/eclipse/keyple/calypso/transaction/CalypsoPoTest.java
- java/component/keyple-calypso/src/test/java/org/eclipse/keyple/calypso/transaction/FileDataTest.java
Signed-off-by: Andrei Cristea <andrei.cristea019@gmail.com>
> feat: KEYP-31: add session management to CalypsoPo

- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/RemoteSePluginImpl.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/VirtualObservableReaderImpl.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/VirtualReaderImpl.java
- java/component/keyple-plugin/remotese/src/test/java/org/eclipse/keyple/plugin/remotese/integration/VirtualReaderEventTest.java
> bug/keyp-193 : move onRemoteReaderEvent to ObservableVirtualReader

- Jenkinsfile
- android/keyple-plugin/android-nfc/build.gradle
- android/keyple-plugin/android-omapi/build.gradle
- build.gradle
- java/component/keyple-calypso/build.gradle
- java/component/keyple-core/build.gradle
- java/component/keyple-plugin/pcsc/build.gradle
- java/component/keyple-plugin/remotese/build.gradle
- java/component/keyple-plugin/stub/build.gradle
- java/example/calypso/android/nfc/build.gradle
- java/example/calypso/android/omapi/build.gradle
Add keyple_version to plugin build
Signed-off-by: Brice Ruppen <brice.ruppen@armotic.fr>
> Jenkinsfile: kill daemons to lower memory usage

- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/command/sam/parser/security/UnlockRespPars.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/transaction/SamSelectionRequest.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/transaction/SamSelector.java
- java/component/keyple-calypso/src/test/java/org/eclipse/keyple/calypso/transaction/SamSelectionRequestTest.java
- java/component/keyple-calypso/src/test/java/org/eclipse/keyple/calypso/transaction/SamSelectorTest.java
- the Unlock command is added when an unlock data is set in the SamSelector.
> feat: KEYP-311 add an Unlock command executed during the SAM selection

- ReleaseNotes.md
in preparation for the alpha 2 release
> doc: ALPHA-2 update of the release notes 

- java/example/calypso/android/omapi/src/main/kotlin/org/eclipse/keyple/example/calypso/android/omapi/activity/CalypsoExamplesActivity.kt
- java/example/calypso/android/omapi/src/main/kotlin/org/eclipse/keyple/example/calypso/android/omapi/activity/CoreExamplesActivity.kt
Signed-off-by: Meddy Menzikoff <m.menzikoff@oneclickflare.fr>
> Fix: Spotless alert

- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/command/AbstractApduCommandBuilder.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/command/AbstractApduResponseParser.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/command/AbstractIso7816CommandBuilder.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/command/SeCommand.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/command/exception/KeypleSeCommandException.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/command/exception/KeypleSeCommandUnknownStatusException.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/command/package-info.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/selection/SeResource.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/PluginFactory.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/SeProxyService.java
Signed-off-by: Meddy Menzikoff <m.menzikoff@oneclickflare.fr>
> Refact: WCAPS-329 Improve javadoc

- android/keyple-plugin/android-omapi/src/main/kotlin/org/eclipse/keyple/plugin/android/omapi/se/AndroidOmapiReader.kt
- android/keyple-plugin/android-omapi/src/main/kotlin/org/eclipse/keyple/plugin/android/omapi/simalliance/AndroidOmapiReader.kt
- android/keyple-plugin/android-omapi/src/test/kotlin/org/eclipse/keyple/plugin/android/omapi/AbstractAndroidOmapiReaderTest.kt
- android/keyple-plugin/android-omapi/src/test/kotlin/org/eclipse/keyple/plugin/android/omapi/se/AndroidOmapiReaderTest.kt
- android/keyple-plugin/android-omapi/src/test/kotlin/org/eclipse/keyple/plugin/android/omapi/simalliance/AndroidOmapiReaderTest.kt
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/message/AnswerToReset.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/message/ApduRequest.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/message/ChannelControl.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/message/ProxyReader.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/message/SeResponse.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/message/SelectionStatus.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/plugin/reader/AbstractLocalReader.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/plugin/reader/AbstractObservableLocalReader.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/plugin/reader/AbstractReader.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/seproxy/plugin/reader/SmartSelectionReader.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/selection/AbstractMatchingSeTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/message/SeResponseTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/reader/AbsLocalReaderSelectionTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/reader/AbsLocalReaderTransmitTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/reader/AbsObservableLocalReaderTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/reader/AbsReaderTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/reader/AbsSmartPresenceTheadedReaderTest.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/reader/BlankAbstractLocalReader.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/reader/BlankAbstractReader.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/seproxy/plugin/reader/BlankSmartSelectionReader.java
- java/component/keyple-plugin/pcsc/src/main/java/org/eclipse/keyple/plugin/pcsc/PcscPluginImpl.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/VirtualObservableReaderImpl.java
- java/component/keyple-plugin/remotese/src/main/java/org/eclipse/keyple/plugin/remotese/pluginse/VirtualReaderImpl.java
- java/component/keyple-plugin/remotese/src/test/java/org/eclipse/keyple/plugin/remotese/integration/VirtualReaderEventTest.java
- java/component/keyple-plugin/stub/src/test/java/org/eclipse/keyple/plugin/stub/StubReaderTest.java
> refact: KEYP-338 Refactor AbstractLocalReader

- java/component/keyple-plugin/stub/src/main/java/org/eclipse/keyple/plugin/stub/StubSecureElement.java
- allows to accept varying APDUs
> feat: KEYP-351 Adds the ability to process regex to the StubElement

- README.md
- android/keyple-plugin/android-nfc/src/main/kotlin/org/eclipse/keyple/plugin/android/nfc/AbstractAndroidNfcReader.kt
- android/keyple-plugin/android-nfc/src/main/kotlin/org/eclipse/keyple/plugin/android/nfc/AndroidNfcPluginFactory.kt
- android/keyple-plugin/android-nfc/src/main/kotlin/org/eclipse/keyple/plugin/android/nfc/AndroidNfcPluginImpl.kt
- android/keyple-plugin/android-nfc/src/main/kotlin/org/eclipse/keyple/plugin/android/nfc/AndroidNfcReader.kt
- android/keyple-plugin/android-nfc/src/main/kotlin/org/eclipse/keyple/plugin/android/nfc/AndroidNfcReaderPostNImpl.kt
- android/keyple-plugin/android-nfc/src/main/kotlin/org/eclipse/keyple/plugin/android/nfc/AndroidNfcReaderPreNImpl.kt
- android/keyple-plugin/android-nfc/src/test/kotlin/org/eclipse/keyple/plugin/android/nfc/AndroidNfcPluginFactoryTest.kt
- android/keyple-plugin/android-nfc/src/test/kotlin/org/eclipse/keyple/plugin/android/nfc/AndroidNfcPluginImplTest.kt
- android/keyple-plugin/android-nfc/src/test/kotlin/org/eclipse/keyple/plugin/android/nfc/AndroidNfcReaderPostNImplTest.kt
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/plugin/reader/AbstractObservableLocalReader.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/plugin/reader/ObservableReaderStateService.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/plugin/reader/BlankObservableLocalReader.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/plugin/reader/BlankPresenceWaitForCardBlockingThreadedReader.java
- java/component/keyple-core/src/test/java/org/eclipse/keyple/core/plugin/reader/BlankWaitForCardInsertionBlockingThreadedReader.java
- java/component/keyple-plugin/pcsc/src/main/java/org/eclipse/keyple/plugin/pcsc/AbstractPcscReader.java
- java/component/keyple-plugin/stub/src/main/java/org/eclipse/keyple/plugin/stub/StubReaderImpl.java
- java/example/calypso/android/nfc/src/main/kotlin/org/eclipse/keyple/example/activity/AbstractExampleActivity.kt
- java/example/calypso/android/nfc/src/main/kotlin/org/eclipse/keyple/example/activity/CalypsoExamplesActivity.kt
- java/example/calypso/android/nfc/src/main/kotlin/org/eclipse/keyple/example/activity/CoreExamplesActivity.kt
- java/example/calypso/android/nfc/src/main/kotlin/org/eclipse/keyple/example/util/Extensions.kt
- java/example/calypso/android/omapi/src/main/kotlin/org/eclipse/keyple/example/calypso/android/omapi/activity/ExamplesActivity.kt
+ Implements method 'onStartDetection' and 'onStopDetection' in AbstractObservableLocalReader.java
Signed-off-by: Youssef Amrani <youssef.amrani@yamapps.fr>
> Keyple plugin handles Android NFC enabling/disabling

- android/keyple-plugin/android-nfc/build.gradle
- android/keyple-plugin/android-nfc/src/main/kotlin/org/eclipse/keyple/plugin/android/nfc/AbstractAndroidNfcReader.kt
- android/keyple-plugin/android-nfc/src/main/kotlin/org/eclipse/keyple/plugin/android/nfc/AndroidNfcReader.kt
- android/keyple-plugin/android-nfc/src/main/kotlin/org/eclipse/keyple/plugin/android/nfc/AndroidNfcReaderPostNImpl.kt
- android/keyple-plugin/android-nfc/src/test/kotlin/org/eclipse/keyple/plugin/android/nfc/AndroidNfcReaderPostNImplTest.kt
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/plugin/SmartInsertionMonitoringJob.java
- java/component/keyple-core/src/main/java/org/eclipse/keyple/core/plugin/WaitForCardInsertionBlocking.java
- java/example/generic/android/nfc/settings.gradle
- java/example/generic/android/nfc/src/main/kotlin/org/eclipse/keyple/example/activity/AbstractExampleActivity.kt
- java/example/generic/android/nfc/src/main/kotlin/org/eclipse/keyple/example/util/Extensions.kt
Signed-off-by: Youssef Amrani <youssef.amrani@yamapps.fr>
> Remove Android NFC plugin parameters, replaced by specific properties

- README.md
> update(readme.md) : fix gradle path

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- NOTICE.md
- README.md
- java/component/keyple-calypso/README.md
- java/component/keyple-core/README.md
- java/component/keyple-plugin/pcsc/README.md
- java/component/keyple-plugin/stub/README.md
Signed-off-by: Ludovic Teixeira Costa <ludovic.teixeiracosta@calypsonet.org>
> Docs: Add legal information

- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/transaction/SamSelector.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/transaction/sammanager/SamIdentifier.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/transaction/sammanager/SamResourceManager.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/transaction/sammanager/SamResourceManagerDefault.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/transaction/sammanager/SamResourceManagerFactory.java
- java/component/keyple-calypso/src/main/java/org/eclipse/keyple/calypso/transaction/sammanager/SamResourceManagerPool.java
- java/component/keyple-calypso/src/test/java/org/eclipse/keyple/calypso/transaction/SamSelectorTest.java
- java/component/keyple-calypso/src/test/java/org/eclipse/keyple/calypso/transaction/sammanager/ManagedSamResourceManagerDefaultTest.java
- java/component/keyple-calypso/src/test/java/org/eclipse/keyple/calypso/transaction/sammanager/ManagedSamResourceManagerPoolTest.java
and move them to a separate package
> refact: KEYP-371 Mark SAM manager classes as deprecated 

- README.md
- android/README.md
- java/component/keyple-core/README.md
> update(doc) : update main readme
